### ISSUE TITLE
How to replicate the paper's analysis?

### ISSUE THREAD

**Issue by athowes** [adrian-lison/nowcast-transmission#1]
Hi Adrian,

I'd like to do some work on models similar to those implemented in `epinowcast`. I think building on your work here would be the best place to start as what you have here is a bit more stripped back / research-y than in the `epinowcast` repo itself.

To get started with this, I thought it'd be good for me to try to replicate the analysis in your paper. Do you know how I'd go about doing this?

In [`code/`](https://github.com/adrian-lison/generative-nowcasting/tree/main/code) I can see `models/` containing the `.stan` files and `utils/`. Is there a script somewhere for using the functions in `utils/` to run the analysis?

Best wishes,
Adam

**Comment by adrian-lison** [comment]
Hey Adam,

of course! This here is the work-in-progress repo that also contains stuff not in the paper. The analyses from the paper are in a separate repo at https://github.com/adrian-lison/generative-nowcasting-study. The README in there should explain the structure, but if you have questions, just let me know. You might need a HPC though if you want to run all the analyses because there are lots of simulation runs.

I think I will add a link to the study repo in the README.

Best
Adrian
